version: "3.8"

services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017/fastapi_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=fastapi_db
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
